name: Deploy Python App

on:
  push:
    branches:
      - main  # Triggers the workflow when code is pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      run: |
        bash ./deploy.sh
      # env:
      #   SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #   SSH_USER: "ridhwan"
      #   SERVER_HOST: "81.17.101.185"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        
